import React, { useState } from 'react';
import { FamilyMember } from './FamilyTree';

interface TimelineEntry {
  id: string;
  year: string;
  title: string;
  summary: string;
  location: string;
  people: string[];
  culturalContext?: { costOfLiving: string; dailyLife: string; event: string };
  [key: string]: any;
}

interface Props {
  timeline: TimelineEntry[];
  familyMembers: FamilyMember[];
}

const ShareView: React.FC<Props> = ({ timeline, familyMembers }) => {
  const [copied, setCopied] = useState(false);

  const exportData = {
    exportedAt: new Date().toISOString(),
    heritageKeeper: true,
    version: '1.0',
    timeline,
    familyMembers,
    stats: {
      memories: timeline.length,
      familyMembers: familyMembers.length,
      locations: [...new Set(timeline.map((e) => e.location).filter(Boolean))].length,
    },
  };

  const handleExport = () => {
    const json = JSON.stringify(exportData, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `heritage-keeper-export-${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyLink = () => {
    const encoded = btoa(JSON.stringify(exportData));
    const shortPreview = `Heritage Keeper: ${timeline.length} memories, ${familyMembers.length} family members`;
    navigator.clipboard.writeText(shortPreview).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handlePdfExport = () => {
    const win = window.open('', '_blank');
    if (!win) return;

    const html = `<!DOCTYPE html>
<html><head>
<title>Heritage Keeper - Family Timeline</title>
<style>
  body { font-family: Georgia, serif; max-width: 700px; margin: 40px auto; color: #1a1a1a; }
  h1 { font-size: 28px; border-bottom: 2px solid #7c3aed; padding-bottom: 8px; }
  .stats { color: #666; margin-bottom: 32px; }
  .entry { margin-bottom: 32px; page-break-inside: avoid; }
  .entry h2 { font-size: 18px; margin-bottom: 4px; }
  .entry .year { color: #7c3aed; font-weight: bold; }
  .entry .summary { color: #444; line-height: 1.6; }
  .entry .location { color: #059669; font-style: italic; }
  .entry .context { background: #f7f7f8; padding: 12px; border-radius: 8px; margin-top: 8px; font-size: 14px; }
  .entry .people { color: #7c3aed; font-size: 13px; }
  .family { margin-top: 40px; border-top: 2px solid #7c3aed; padding-top: 16px; }
  .member { display: inline-block; margin: 4px 8px 4px 0; padding: 4px 12px; background: #ede9fe; border-radius: 20px; font-size: 13px; }
  @media print { body { margin: 20px; } }
</style>
</head><body>
<h1>Heritage Keeper - Family Timeline</h1>
<p class="stats">${timeline.length} memories &bull; ${familyMembers.length} family members &bull; Exported ${new Date().toLocaleDateString()}</p>
${timeline.map(e => `
<div class="entry">
  <span class="year">${e.year}</span>
  <h2>${e.title}</h2>
  ${e.location ? `<p class="location">\ud83d\udccd ${e.location}</p>` : ''}
  <p class="summary">${e.summary}</p>
  ${e.people?.length ? `<p class="people">People: ${e.people.join(', ')}</p>` : ''}
  ${e.culturalContext?.costOfLiving || e.culturalContext?.dailyLife || e.culturalContext?.event ? `<div class="context">
    ${e.culturalContext.costOfLiving ? `<p><strong>Cost of Living:</strong> ${e.culturalContext.costOfLiving}</p>` : ''}
    ${e.culturalContext.dailyLife ? `<p><strong>Daily Life:</strong> ${e.culturalContext.dailyLife}</p>` : ''}
    ${e.culturalContext.event ? `<p><strong>Events:</strong> ${e.culturalContext.event}</p>` : ''}
  </div>` : ''}
</div>`).join('')}
${familyMembers.length > 0 ? `
<div class="family">
  <h2>Family Tree</h2>
  ${familyMembers.map(m => `<span class="member">${m.name} - ${m.relationship}</span>`).join('')}
</div>` : ''}
<p style="color:#999;margin-top:40px;font-size:12px;">Generated by Heritage Keeper</p>
</body></html>`;

    win.document.write(html);
    win.document.close();
    win.print();
  };

  const hasData = timeline.length > 0 || familyMembers.length > 0;

  return (
    <div style={{ maxWidth: 720 }}>
      <h2 style={{ fontSize: 24, fontWeight: 800, marginBottom: 8 }}>
        Share &amp; Collaborate
      </h2>
      <p style={{ color: 'var(--text-secondary)', marginBottom: 28, lineHeight: 1.6 }}>
        Preserve your findings. Export your family history, or share a snapshot with relatives.
      </p>

      {/* Data Portability */}
      <div className="sidebar-card" style={{ marginBottom: 20 }}>
        <h4 className="sidebar-card-title purple">&#x1f4e6; Data Portability</h4>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
          {/* Export */}
          <div style={{
            padding: 20,
            background: 'var(--bg)',
            borderRadius: 'var(--radius)',
            border: '1px solid var(--border)',
          }}>
            <p style={{ fontWeight: 700, marginBottom: 6 }}>Export Timeline</p>
            <p style={{ fontSize: 13, color: 'var(--text-secondary)', marginBottom: 14, lineHeight: 1.5 }}>
              Download your complete family history as a portable JSON file.
              Perfect for backup or sharing.
            </p>
            <button
              className="btn-post"
              onClick={handleExport}
              disabled={!hasData}
              style={{ width: '100%' }}
            >
              &#x2B07; Download JSON
            </button>
          </div>

          {/* Copy Summary */}
          <div style={{
            padding: 20,
            background: 'var(--bg)',
            borderRadius: 'var(--radius)',
            border: '1px solid var(--border)',
          }}>
            <p style={{ fontWeight: 700, marginBottom: 6 }}>Share Summary</p>
            <p style={{ fontSize: 13, color: 'var(--text-secondary)', marginBottom: 14, lineHeight: 1.5 }}>
              Copy a summary of your family history to share with relatives
              via email or messaging.
            </p>
            <button
              className="btn-post"
              onClick={handleCopyLink}
              disabled={!hasData}
              style={{
                width: '100%',
                background: copied ? 'var(--success)' : undefined,
              }}
            >
              {copied ? '\u{2714} Copied!' : '\u{1F4CB} Copy Summary'}
            </button>
          </div>
        </div>

        <div style={{ marginTop: 12, padding: 20, background: 'var(--bg)', borderRadius: 'var(--radius)', border: '1px solid var(--border)' }}>
          <p style={{ fontWeight: 700, marginBottom: 6 }}>Export as PDF</p>
          <p style={{ fontSize: 13, color: 'var(--text-secondary)', marginBottom: 14, lineHeight: 1.5 }}>
            Generate a print-ready document of your family timeline. Opens in a new tab for printing or saving as PDF.
          </p>
          <button className="btn-post" onClick={handlePdfExport} disabled={!hasData} style={{ width: '100%' }}>
            &#x1f4c4; Print / Save as PDF
          </button>
        </div>
      </div>

      {/* Stats */}
      {hasData && (
        <div className="sidebar-card" style={{ marginBottom: 20 }}>
          <h4 className="sidebar-card-title amber">&#x1f4ca; Your Heritage</h4>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 16, textAlign: 'center' }}>
            <div>
              <p style={{ fontSize: 32, fontWeight: 800, color: 'var(--primary)' }}>{timeline.length}</p>
              <p style={{ fontSize: 12, color: 'var(--text-muted)', fontWeight: 600 }}>Memories</p>
            </div>
            <div>
              <p style={{ fontSize: 32, fontWeight: 800, color: 'var(--primary)' }}>{familyMembers.length}</p>
              <p style={{ fontSize: 12, color: 'var(--text-muted)', fontWeight: 600 }}>Family Members</p>
            </div>
            <div>
              <p style={{ fontSize: 32, fontWeight: 800, color: 'var(--primary)' }}>
                {[...new Set(timeline.map((e) => e.location).filter(Boolean))].length}
              </p>
              <p style={{ fontSize: 12, color: 'var(--text-muted)', fontWeight: 600 }}>Locations</p>
            </div>
          </div>
        </div>
      )}

      {/* How to Collaborate */}
      <div className="sidebar-card">
        <h4 className="sidebar-card-title purple">&#x1f91d; How to Collaborate</h4>
        <div style={{ display: 'flex', gap: 20 }}>
          {[
            { step: '1', title: 'Record Memories', desc: 'Share stories by speaking or typing with the Heritage Keeper agent.' },
            { step: '2', title: 'Export & Share', desc: 'Use the JSON export to create a file, or copy the summary to share.' },
            { step: '3', title: 'Merge History', desc: 'Family members can record their own memories and combine timelines.' },
          ].map((item) => (
            <div key={item.step} style={{ flex: 1, textAlign: 'center' }}>
              <div aria-hidden="true" style={{
                width: 36, height: 36, borderRadius: '50%', background: 'var(--primary)',
                color: 'white', fontWeight: 800, fontSize: 16,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                margin: '0 auto 10px',
              }}>
                {item.step}
              </div>
              <p style={{ fontWeight: 700, fontSize: 14, marginBottom: 4 }}>{item.title}</p>
              <p style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.5 }}>{item.desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Clear All Data */}
      <div className="sidebar-card" style={{ marginTop: 20, borderColor: '#fecaca' }}>
        <h4 className="sidebar-card-title" style={{ color: 'var(--danger)' }}>&#x26a0; Data Management</h4>
        <p style={{ fontSize: 13, color: 'var(--text-secondary)', marginBottom: 12, lineHeight: 1.5 }}>
          Clear all locally stored memories and family tree data. This cannot be undone.
        </p>
        <button
          className="btn-post"
          onClick={() => {
            if (window.confirm('Are you sure? This will permanently delete all your saved memories and family tree data.')) {
              localStorage.removeItem('hk_timeline');
              localStorage.removeItem('hk_family');
              window.location.reload();
            }
          }}
          style={{ width: '100%', background: 'var(--danger)' }}
        >
          Clear All Data
        </button>
      </div>
    </div>
  );
};

export default ShareView;
